### ISSUE TITLE
CurrentPage not updated when calling setCurrentPage

### ISSUE THREAD

**Issue by m42e** [amirdew/CollectionViewPagingLayout#11]
When calling `setCurrentPage` with a specific page number, the internal variable `currentPage` in `CollectionViewPagingLayout` is not updated. 

This causes a possibly far to large step, even in the wrong direction when `goToNextPage` or `goToPreviousPage` is called.

**Comment by amirdew** [comment]
Hi Matthias, Thanks for reporting the issue, 
I made a pull request for this, could you check and confirm it's fixed?
thanks
