### ISSUE TITLE
Forcing semanticContentAttribute fails

### ISSUE THREAD

**Issue by elrond140** [amirdew/CollectionViewPagingLayout#16]
When you set 

`collectionView.semanticContentAttribute = .forceRightToLeft`

I believe that the expected behavior should be that the collectionView scrolls from right to left, instead of the standard left to right which is the default in most western languages. However, this has no effect.

**Comment by amirdew** [comment]
Unfortunately right to left is not supported at the moment
however you can achieve that by scrolling your collection view programmatically to the end offset
