### ISSUE TITLE
setCurrentPage(animated: false) with ScaleTransformView causes a stack of cells to form

### ISSUE THREAD

**Issue by elrond140** [amirdew/CollectionViewPagingLayout#17]
I have a ScaleTransformView, with a layout of 3 visible cells, that seems to work as expected.

However, when calling **setCurrentPage(animated = false)**, each of the 'visible cells' occupy the same frame as the 'primary' cell, causing a stack of three cells. As soon as you start dragging the primary cell, each of the 'visible cells' fall to their correct locations respectively. 

Setting **animated: true** results in expected behavior, however having it as **true** isn't ideal for my use case. I've already tried calling layoutIfNeeded(), but that seems to have no effect.

**Comment by amirdew** [comment]
Hi, thanks for reporting this issue,
I think I saw a similar issue and I fixed it in another branch.    
could you check that and see if it fixes the issue for you or not,  you can do it by specifying the branch in your pod file:
```
pod 'CollectionViewPagingLayout', :git => 'https://github.com/amirdew/CollectionViewPagingLayout.git', :branch => 'macApp'
```
if it does fix the issue we can close this and I'll try to merge the branch asap.  
if it doesn't could you please make a sample project on your account and mention the link to it here so I can replicate the issue and fix it

thanks

**Comment by elrond140** [comment]
Test Project Demonstrating Issue: https://github.com/elrond140/ScaleTest

Some Notes:

1. Just by scrolling to a random cell and hitting the Go button several times, you should see what I mean. Either, the first, second, or third visible cells disappear until you move the collectionview. 

2. (not in sample project) I've noticed similar behavior in a blank cell being left behind after deleting data from the data source(on a collectionview sourced by a fetchedresultscontroller/coredata). When the data was deleted, the middle cell was gone, but the two other cells remained. As soon as you moved the collection, everything sorted itself out. 

3. (not in sample project) Calling reloadData on the collectionview will sometimes cause the first or third cells to temporarily take the place of the 'main' second cell. As soon as you move the collectionview, it would correct itself instantly. 

I'm guessing most of these issues, if not all, are related.

**Comment by amirdew** [comment]
Thanks, 
yes, you are right the issues are related, I can see for some reasons the layout doesn't get invalidated.
I can fix all the issues by invalidating it manually on `viewDidLayoutSubviews` and after setting the page:
viewController.swift
```swift
   // ...
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        myCollectionView.reloadData()
        myCollectionView.performBatchUpdates({
            self.myCollectionView.collectionViewLayout.invalidateLayout()
        })
    }
  // ...
   @objc func goToButtonPressed(){
        print("goTo-pressed")
        layout.setCurrentPage(4, animated: false)
        myCollectionView.reloadData()
        myCollectionView.performBatchUpdates({
            self.myCollectionView.collectionViewLayout.invalidateLayout()
        })
    }
```

**Comment by elrond140** [comment]
Such an extremely simple answer - I feel a bit stupid now. I thought I had already tried something like this, but I probably just messed up the order of operations. So far, everything is now working as expected. 

Thanks for the help! Feel free to close this issue, but I'll keep this issue open for now in case you first want to release a fix within the source.

**Comment by amirdew** [comment]
It was weird to me too and still is, 
I want to investigate more about it and I hope I can add something to the layout that makes calling these methods unnecessary.
yeah let's leave the issue open

**Comment by elrond140** [comment]
Note for anyone trying to implement the same functions that are inside `goToButtonPressed()` in the above example into either `viewDidLoad()` or `viewWillAppear()`: 

Make sure you call `myCollectionView.layoutIfNeeded()` before you try to call `layout.setCurrentPage(##, animated: true/false)`. If you don't, the current page will remain at index 0.

**Comment by amirdew** [comment]
I ended up calling `invalidateLayout` in the library when we set the current page without animation.     
So, with the new version(0.3.0) you don't need to call that manually
https://github.com/amirdew/CollectionViewPagingLayout/pull/20/commits/61280d0b9c20fbd3c6a12a5c7aba0c87956684c1

I close this issue
