### ISSUE TITLE
Type of expression is ambiguous without more context (\.attributes)

### ISSUE THREAD

**Issue by belalmedhat97** [amirdew/CollectionViewPagingLayout#22]
in collectionviewpaginglayoutdelegate 
problem occurs
![Screen Shot 2020-07-13 at 1 24 28 AM](https://user-images.githubusercontent.com/51267587/87258969-260a9900-c4a8-11ea-84f2-b6ee92c96ef8.png)

**Comment by amirdew** [comment]
Make sure you use swift 5 and Xcode 11

**Comment by belalmedhat97** [comment]
already using xcode 11 and swift

**Comment by amirdew** [comment]
could you share a sample project? what dependency management system do you use?

**Comment by belalmedhat97** [comment]
i just add the pod using cocoapods then the error occur in my project in collectionview paging layout delegate

**Comment by amirdew** [comment]
okay, this is a Swift5.2 feature 
you should use Xcode >= 11.4

https://i.stack.imgur.com/TevRZ.jpg

I just made a project and it works


if you do use a new Xcode and it still doesn't work
make a new project and share that
because it's not reproducable for me
