### ISSUE TITLE
Blur issue

### ISSUE THREAD

**Issue by purepure** [amirdew/CollectionViewPagingLayout#24]
When i select ScaleTransformViewOptions with blurEffectEnabled = true, there is an issue about the transparent layer. Please check the screenshot
![Simulator Screen Shot - iPhone 11 - 2020-08-07 at 14 12 02](https://user-images.githubusercontent.com/3175469/89619450-2ab04a80-d8b8-11ea-9a27-421f35fbce8d.png)

**Comment by amirdew** [comment]
correct, yes I'm aware of this issue, this is actually how `UIVisualEffectView` works.    
so I think there is not much that I can do about it, you need to use this on white background or black background with dark blur stye

**Comment by purepure** [comment]
Thank for the reply. Your lib work like a charm with the other layout!

**Comment by amirdew** [comment]
thank you for using and feedback!
