### ISSUE TITLE
transformed cells disappear when capture in snapshot mode

### ISSUE THREAD

**Issue by uxight** [amirdew/CollectionViewPagingLayout#25]
I add this code below(PagingLayoutSamples Project), It works well in simulator but in real device all transformed cells disappear.
(collectionView.isPagingEnabled = false) && content offset is not in paging location

extension ShapesViewController: UICollectionViewDelegate {

    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        guard collectionView != self.layoutTypeCollectionView else { return }
        UIGraphicsBeginImageContextWithOptions(view.bounds.size, view.isOpaque, 0)
        defer { UIGraphicsEndImageContext() }
        view.drawHierarchy(in: view.bounds, afterScreenUpdates: true)
        let image = UIGraphicsGetImageFromCurrentImageContext() ?? UIImage()
        
        let imageView = (self.view.viewWithTag(432) as? UIImageView) ?? UIImageView(frame: CGRect(x: 30, y: 50, width: 190, height: 340))
        imageView.contentMode = .scaleAspectFit
        imageView.tag = 432
        self.view.addSubview(imageView)
        imageView.image = image
    }
}

How can I solve this?

**Comment by amirdew** [comment]
Transformed cells in `snapshot mode` are snapshots! (used this [func](https://developer.apple.com/documentation/uikit/uiview/1622531-snapshotview)) and the original view is hidden!             
apparently `drawHierarchy` doesn't draw snapshot views! I don't know why! it might be an issue in SDK!
so I don't think there is anything I can do about it!
