### ISSUE TITLE
Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by tranquocviet226** [amirdew/CollectionViewPagingLayout#28]
Hi. I found an error 
![Screen Shot 2020-10-08 at 23 12 54](https://user-images.githubusercontent.com/57559641/95485468-f93d2380-09bb-11eb-88b0-6345d343db5c.png)

**Comment by amirdew** [comment]
Hi, this is a Swift 5.2 feature
you should use Xcode >= 11.4

**Comment by tranquocviet226** [comment]
Hi Amir, I used Xcode version 11.4

Vào Th 5, 8 thg 10, 2020 vào lúc 23:23 Amir Khorsandi <
notifications@github.com> đã viết:
