### ISSUE TITLE
Extensions must not contain stored properties

### ISSUE THREAD

**Issue by tranquocviet226** [amirdew/CollectionViewPagingLayout#29]
![Screen Shot 2020-10-11 at 09 40 24](https://user-images.githubusercontent.com/57559641/95669043-d8d0bd00-0ba5-11eb-82b8-63095be034af.png)

Hi Amir, How can I fix this error?

**Comment by amirdew** [comment]
if you want to use extensions, you shouldn't define it as a stored property (it's a swift compiler rule), you can do it like this:
```swift
var scaleOptions: ScaleTransformViewOptions {
     ScaleTransformViewOptions(
      // ...
     )
}
```
or define it in the cell class itself

**Comment by tranquocviet226** [comment]
Sorry Amir, I'm newbie.
I want my screen to show part of the next cell and previous cell like your sample.
But my cell is always full screen like this:

**Comment by tranquocviet226** [comment]
Sorry amir, I'm newbie.
I want my screen to show part of the next cell and previous cell like your sample.
But my cell is always full screen like this:


![Screen Shot 2020-10-11 at 17 48 07](https://user-images.githubusercontent.com/57559641/95676697-2111ce80-0bea-11eb-89f8-ce1941c1889b.png)

**Comment by amirdew** [comment]
No worries, make sure you are adding padding in your cell view,
the easiest way is using the macOS app, it generates code for you so you only need to customize your cell view,

for instance you can use this:
```swift
import UIKit

// Make sure you added this dependency to your project
// More info at https://bit.ly/CVPagingLayout
import CollectionViewPagingLayout

// The cell class needs to conform to `ScaleTransformView` protocol
// to be able to provide the transform options
class MyCell: UICollectionViewCell, ScaleTransformView {
    
    var scaleOptions = ScaleTransformViewOptions(
        minScale: 0.60,
        maxScale: 1.00,
        scaleRatio: 0.40,
        translationRatio: .init(x: 0.66, y: 0.20),
        minTranslationRatio: .init(x: -5.00, y: -5.00),
        maxTranslationRatio: .init(x: 2.00, y: 0.00),
        keepVerticalSpacingEqual: true,
        keepHorizontalSpacingEqual: true,
        scaleCurve: .linear,
        translationCurve: .linear,
        shadowEnabled: true,
        shadowColor: .black,
        shadowOpacity: 0.60,
        shadowRadiusMin: 2.00,
        shadowRadiusMax: 13.00,
        shadowOffsetMin: .init(width: 0.00, height: 2.00),
        shadowOffsetMax: .init(width: 0.00, height: 6.00),
        shadowOpacityMin: 0.10,
        shadowOpacityMax: 0.10,
        blurEffectEnabled: false,
        blurEffectRadiusRatio: 0.40,
        blurEffectStyle: .light,
        rotation3d: nil,
        translation3d: nil
    )

    // The card view that we apply effects on
    var card: UIView!
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setup()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setup()
    }
    
    func setup() {
        // Adjust the card view frame you can use Autolayout too
        let cardFrame = CGRect(x: 80,
                               y: 100,
                               width: frame.width - 160,
                               height: frame.height - 200)
        card = UIView(frame: cardFrame)
        card.backgroundColor = .gray
        contentView.addSubview(card)
    }
}

// A simple View Controller that filled with a UICollectionView
// You can use `UICollectionViewController` too
class ViewController: UIViewController, UICollectionViewDataSource {
    
    var collectionView: UICollectionView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupCollectionView()
    }
    
    private func setupCollectionView() {
        collectionView = UICollectionView(
            frame: view.frame,
            collectionViewLayout: CollectionViewPagingLayout()
        )
        collectionView.isPagingEnabled = true
        collectionView.register(MyCell.self, forCellWithReuseIdentifier: "cell")
        collectionView.dataSource = self
        view.addSubview(collectionView)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        DispatchQueue.main.async { [weak self] in
            self?.collectionView?.performBatchUpdates({ [weak self] in
                self?.collectionView?.collectionViewLayout.invalidateLayout()
            })
        }
    }
    
    func collectionView(
        _ collectionView: UICollectionView,
        numberOfItemsInSection section: Int
    ) -> Int {
        10
    }
    
    func collectionView(
        _ collectionView: UICollectionView,
        cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        collectionView.dequeueReusableCell(
            withReuseIdentifier: "cell",
            for: indexPath
        )
    }
    
}
```

**Comment by tranquocviet226** [comment]
Sorry Amir again,
I followed your instructions but my background color is always black. If I change the background color the next cell and previous cell are not present.
![Screen Shot 2020-10-11 at 19 43 29](https://user-images.githubusercontent.com/57559641/95679033-7eae1700-0bfa-11eb-95ff-a2ba703b5ffa.png)

**Comment by amirdew** [comment]
could you share your code?

**Comment by tranquocviet226** [comment]
Hey Amir, I put my collection view inside a table cell.
This is my TableCell
`
import UIKit
import CollectionViewPagingLayout

class HotIdolTableCell: UITableViewCell {
    var collectionView: UICollectionView!
    
    override func awakeFromNib() {
        super.awakeFromNib()
      
        setupCollectionView()
    }
    
    private func setupCollectionView() {
        collectionView = UICollectionView(
            frame: contentView.frame,
            collectionViewLayout: CollectionViewPagingLayout()
        )
        collectionView.isPagingEnabled = true
        collectionView.register(HotIdolCollectionCell.self, forCellWithReuseIdentifier: "HotIdolCollectionCell")
        collectionView.dataSource = self
        contentView.addSubview(collectionView)
    }
    override func layoutSubviews() {
        super.layoutSubviews()
        // do your thing
        DispatchQueue.main.async { [weak self] in
            self?.collectionView?.performBatchUpdates({ [weak self] in
                self?.collectionView?.collectionViewLayout.invalidateLayout()
            })
        }
    }
}


extension HotIdolTableCell: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout  {

    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 5
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "HotIdolCollectionCell", for: indexPath) as? HotIdolCollectionCell else {return UICollectionViewCell()}
        
        return cell
    }    
}

And Collection Cell 

import UIKit
import CollectionViewPagingLayout

class HotIdolCollectionCell: UICollectionViewCell, ScaleTransformView {
    var scaleOptions = ScaleTransformViewOptions(
        minScale: 0.6,
        scaleRatio: 0.4,
        translationRatio: CGPoint(x: 0.66, y: 0.2),
        maxTranslationRatio: CGPoint(x: 2, y: 0)
    )
    
    override func awakeFromNib() {
        super.awakeFromNib()
        // Initialization code
        
        setupUI()
    }

    func setupUI() {
    }

    var card: UIView!
    
    override init(frame: CGRect) {
        super.init(frame: frame)
       
        setup()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setup()
    }
    
    func setup() {
        // Adjust the card view frame you can use Autolayout too
        let cardFrame = CGRect(x: 80,
                               y: 8,
                               width: frame.width - 160,
                               height: frame.height - 16)
        card = UIView(frame: cardFrame)
        card.backgroundColor = .red
        contentView.addSubview(card)
    }
}
`

**Comment by amirdew** [comment]
did you try setting background color for the collection view? `collectionView.backgroundColor = .clear`

**Comment by tranquocviet226** [comment]
Yess, thank you so much!
