### ISSUE TITLE
iOS 8 warning in Xcode 12

### ISSUE THREAD

**Issue by CristianMoisei** [amirdew/CollectionViewPagingLayout#30]
In the latest version of Xcode 12, there is a warning associated with this package if installed via SwiftPM. This is because Xcode 12 drops support for iOS 8 and this package still supports it.
[Screenshot](https://ibb.co/jkR1Scs)

**Comment by amirdew** [comment]
That's just a warning since Xcode 12 doesn't support iOS 8.
I'll remove support for iOS 8 on this library soon,
meanwhile, if the warning really annoys you, you can set the target [manually](https://www.jessesquires.com/blog/2020/07/20/xcode-12-drops-support-for-ios-8-fix-for-cocoapods/)

**Comment by CristianMoisei** [comment]
Thanks @amirdew, that is only possible for pods though right? Not SwiftPM.

**Comment by amirdew** [comment]
right, only for cocoapods

**Comment by amirdew** [comment]
fixed on 0.4.0

**Comment by CristianMoisei** [comment]
Nice, thanks for looking into this.
