### ISSUE TITLE
Info.plist file missing

### ISSUE THREAD

**Issue by SwiftCrew** [amirdew/CollectionViewPagingLayout#31]

**Comment by amirdew** [comment]
I couldn't reproduce this, there are two info.plist file one for the library which is here https://github.com/amirdew/CollectionViewPagingLayout/blob/master/CollectionViewPagingLayout/Info.plist
   
the other one for the samples project which you can find here: 
https://github.com/amirdew/CollectionViewPagingLayout/blob/master/Samples/PagingLayoutSamples/Info.plist
