### ISSUE TITLE
support infinite loop model

### ISSUE THREAD

**Issue by azureplus** [amirdew/CollectionViewPagingLayout#34]
support infinite loop model

**Comment by amirdew** [comment]
You can achieve infinite loop by returning a large number for the number of items and then scroll to the middle at start, take a look at [`CardsViewController.swift`](https://github.com/amirdew/CollectionViewPagingLayout/blob/e364ee1543a94fefee59218422434c5a11b2c7b5/Samples/PagingLayoutSamples/Modules/Cards/CardsViewController.swift)
make sure you specify `numberOfVisibleItems` then the large number has no effect on the performance

**Comment by mikepitre** [comment]
@amirdew how would you suggest achieving this in SwiftUI?
