### ISSUE TITLE
What should I do if I want to designate the animation duration for changing pages?

### ISSUE THREAD

**Issue by airence** [amirdew/CollectionViewPagingLayout#35]
I've tried calling CATransaction.setAnimationDuration: In `CollectionViewPagingLayout.safelySetCurrentPage(_ page: Int, animated: Bool) `,but it dosen't work, and when using UIView Animation to animate the` colletionView.setContenetOffset`, it behaves weirdly

**Comment by hoangdungfuta** [comment]
I think you shouldn't change function `safelySetCurrentPage` , if you want to change page duration, you should change implement in protocol `TransformableView` by function `func transform(progress: CGFloat)`

**Comment by amirdew** [comment]
Unfortunately the animation duration for changing pages is not accessable, 
this library doesn't have any hardcoded animation duration. it's hardcoded in the iOS SDK.

there are some hacky ways to override  it but, they don't work all the time and for all the layouts.
the [accepted answer here](https://stackoverflow.com/questions/12922780/how-do-you-set-the-duration-for-uicollectionview-animations/15146098#15146098) would work (as the writer said it's not AppStore-safe)

although you can't change duration, you can fake it with logarithmic methods! take a look at [card stack example ](https://github.com/amirdew/CollectionViewPagingLayout/blob/e364ee1543a94fefee59218422434c5a11b2c7b5/Samples/PagingLayoutSamples/Modules/Cards/Cell/CardCollectionViewCell.swift) where a card comes up slow but goes down fast!

**Comment by amirdew** [comment]
with the new version (1.0.0) you can specify duration and timing curve using 'DefaultViewAnimator'
