### ISSUE TITLE
How to handle multiple buttons click event in cell?

### ISSUE THREAD

**Issue by deependrag** [amirdew/CollectionViewPagingLayout#36]

**Comment by amirdew** [comment]
Like you do that with a normal CollectionView.
by adding tap gestures or put a button inside the cell

**Comment by deependrag** [comment]
@amirdew It only works on first cell (index 0). It does not work from second cell onwards. The button action or any gesture in cell does not register any event. I tried it on sample project too..

**Comment by amirdew** [comment]
Make sure the zIndex is provided probably,
probably the reason is the first cell is always on top,
check out "Fruits" example,
the counter is part of the cell

**Comment by deependrag** [comment]
Thanks @amirdew after adding zPosition the issue was fixed.

`func zPosition(progress: CGFloat) -> Int {
        if progress < -0.5 {
            return -10
        }
        return Int(-abs(round(progress)))
}`

**Comment by deependrag** [comment]
@amirdew  after adding zPosition (above solution) the cell goes back while transitioning.  What should be the zPosition if i want to send back the cell only after complete transition in stack options?

**Comment by amirdew** [comment]
you can use "progress" value for that,
0 means it's the current page, -1 means it's the previous page, and -0.5 means it's between those 
the above code is for card stack layout where we want to send the card to the back of the stack.

you can return zPosition based on that progress value.

it depends on your layout and what cell you want to be on top,
would you mind share a simple version of your layout?

**Comment by deependrag** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30722359/109831956-05c26100-7c68-11eb-9581-66513aa516ce.gif)

Here i need left to right swipe (opposite of normal collection view) to go to next cell so i did this to achieve that..
`extension CollectionViewPagingLayout {
    public override var flipsHorizontallyInOppositeLayoutDirection: Bool {
        return true
    }
}` 
you can see in gif while cell transitioning the forward cell goes backside without completing the swipe. However this fixed my previous cell action issue but the animation looks weird.

**Comment by amirdew** [comment]
Do you use `StackTransformView` ?
you can use `StackTransformViewOptions.reverse` instead of `flipsHorizontallyInOppositeLayoutDirection` and remove overriding `zPosition`. 
OR   
probably this also works:
```swift
func zPosition(progress: CGFloat) -> Int {
        Int(round(progress))
}
```
I need to see the code in order to help more, 

what you trying to achieve is similar to [`stackReverse`](https://github.com/amirdew/CollectionViewPagingLayout/blob/e364ee1543a94fefee59218422434c5a11b2c7b5/Samples/PagingLayoutSamples/Modules/Shapes/ShapeLayout%2BStackOptions.swift#L67)

<img src=https://camo.githubusercontent.com/05433340e554f945f8c8bd7798c5597624b4413df07c1f352a2f3e5ab9e61d68/68747470733a2f2f616d69722e6170702f6769742f7368617065735f707265766965772f737461636b5f726576657273652e676966 />

**Comment by deependrag** [comment]
@amirdew  yes i have used `StackTransformView`. I have also tried with `StackTransformViewOptions.reverse` but the problem here is i need to swipe from Right to Left to go to next cell. But i want just revese of that i.e. swiping from left to right to go from first cell to second cell with same effect like above. Thats why i flip the layout to get same effect like above but click event did not register from 2nd cell onwards. 

I have also tried this but didnot work
```
func zPosition(progress: CGFloat) -> Int {
        Int(round(progress))
}
```

**Comment by amirdew** [comment]
Could you share your `StackTransformViewOptions` that you use, so I can replicate the layout and find a proper zPosition function for you?

**Comment by deependrag** [comment]
````
var stackOptions = StackTransformViewOptions(
            scaleFactor: 0.11,
            minScale: 0.00,
            maxScale: 1.00,
            maxStackSize: 6,
            spacingFactor: 0.09,
            maxSpacing: nil,
            alphaFactor: 0.00,
            bottomStackAlphaSpeedFactor: 0.90,
            topStackAlphaSpeedFactor: 0.30,
            perspectiveRatio: 0.30,
            shadowEnabled: true,
            shadowColor: .black,
            shadowOpacity: 0.40,
            shadowOffset: .zero,
            shadowRadius: 10.00,
            stackRotateAngel: 0.00,
            popAngle: 0.31,
            popOffsetRatio: .init(width: 0.87, height: -0.30),
            stackPosition: .init(x: -0.66, y: 0.00),
            reverse: false,
            blurEffectEnabled: false,
            maxBlurEffectRadius: 0.00,
            blurEffectStyle: .light
        )

var cardView: UIView {
        contentView
    }
````

This is the workaround for opposite swipe support
````
extension CollectionViewPagingLayout {
    public override var flipsHorizontallyInOppositeLayoutDirection: Bool {
        return true
    }
}
````

Help me find the zPosition so that the actions can be triggered and animation are same

**Comment by amirdew** [comment]
Hey, sorry for delay,
this should work for you:
```swift
func zPosition(progress: CGFloat) -> Int {
        if progress <= -1 {
            return .min
        }
        return -Int(round(progress))
 }
```

**Comment by amirdew** [comment]
If you are using `StackTransformViewOptions.reverse = true` then this would work:
```swift
 func zPosition(progress: CGFloat) -> Int {
        if progress >= 1 {
            return .min
        }
        return Int(round(progress))
   }
```

**Comment by deependrag** [comment]
@amirdew Thank you so much after adding above zposition it worked fine.
