### ISSUE TITLE
Is there a way to have multiple cells appear on the collection view at once?

### ISSUE THREAD

**Issue by alanpridestar** [amirdew/CollectionViewPagingLayout#39]
Hi, thanks for the project, its super impressive. I saw some other issues people are having with the project and tried to use the suggestions you provided, but I am still facing some issues myself. 

It seems like, by design, the cells always take the entire collection view space. Is there any way that I can have multiple cells appear in the collection view?

The issue i'm having is that the appearance is like this:

![Screen Shot 2021-03-29 at 2 05 26 PM](https://user-images.githubusercontent.com/40860015/112829435-cd147c80-9099-11eb-9318-fb2366514c37.png)

The animations of the cells (scaling as I Scroll) work fine, but the other cells appear off screen. 

I think that if my collection view had a larger height, then it would appear normal, but I need to have a small collection view size. I tried manipulating the card size like in other examples you had, but it seems like just the card would get smaller and the cell would remain the same size as the collection view.

**Comment by sharjeelahmed** [comment]
i also facing the same issue . the cells take the entire collection view space. i also want to show some width of left and right cell

**Comment by amirdew** [comment]
Hi, thanks for using the library 
> It seems like, by design, the cells always take the entire collection view space.

that is correct, but that doesn't mean you can't show multiple cells

It's actually very simple, when you design your cell, consider the space around it as part of the cell.
for instance, like this:
<img width="938" alt="Screenshot 2021-03-29 at 18 43 23" src="https://user-images.githubusercontent.com/1938899/112871188-4b374a00-90bf-11eb-95f5-49f6ddfc79fc.png">

then use options to adjust the space between cells (if you use ScaleTransformView `ScaleTransformViewOptions.translationRatio`)

Here is the full code for the above example:
the collection view filled half of the screen and we have multiple cells visible
```swift
import UIKit
import CollectionViewPagingLayout

// The cell class needs to conform to `ScaleTransformView` protocol
// to be able to provide the transform options
class MyCell: UICollectionViewCell, ScaleTransformView {
    
    var scaleOptions = ScaleTransformViewOptions()

    // The card view that we apply transforms on
    var card: UIView!
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setup()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setup()
    }
    
    func setup() {
        // Adjust the card view frame you, can use Autolayout too
        let cardFrame = CGRect(x: 80,
                               y: 40,
                               width: frame.width - 160,
                               height: frame.height - 100)
        card = UIView(frame: cardFrame)
        card.backgroundColor = .gray
        contentView.addSubview(card)
    }
}

// A simple View Controller that filled with a UICollectionView
// You can use `UICollectionViewController` too
class ViewController: UIViewController, UICollectionViewDataSource {
    
    var collectionView: UICollectionView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupCollectionView()
    }
    
    private func setupCollectionView() {
        collectionView = UICollectionView(
            frame: .init(x: 0, y: 0, width: view.frame.width, height: view.frame.height/2),
            collectionViewLayout: CollectionViewPagingLayout()
        )
        collectionView.isPagingEnabled = true
        collectionView.register(MyCell.self, forCellWithReuseIdentifier: "cell")
        collectionView.dataSource = self
        collectionView.backgroundColor = .cyan
        view.addSubview(collectionView)
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        DispatchQueue.main.async { [weak self] in
            self?.collectionView?.performBatchUpdates({ [weak self] in
                self?.collectionView?.collectionViewLayout.invalidateLayout()
            })
        }
    }
    
    func collectionView(
        _ collectionView: UICollectionView,
        numberOfItemsInSection section: Int
    ) -> Int {
        10
    }
    
    func collectionView(
        _ collectionView: UICollectionView,
        cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        collectionView.dequeueReusableCell(
            withReuseIdentifier: "cell",
            for: indexPath
        )
    }
    
}
```

preview:
<img width="452" alt="Screenshot 2021-03-29 at 18 54 03" src="https://user-images.githubusercontent.com/1938899/112872120-49ba5180-90c0-11eb-8e8e-336c8185f39c.png">


You can use `TransformableView -> func zPosition(progress: CGFloat) -> Int` to decided which cell should be on top (clickable)

**Comment by sharjeelahmed** [comment]
thanks . now its working but still i have an issue . collectionview didn't show the small space of next item until we scroll the collectionView . but when it scroll it worked fine . 
![Screenshot 2021-03-30 at 3 29 43 PM](https://user-images.githubusercontent.com/7043500/112975407-0833b000-916d-11eb-81b5-55976e3db745.png)
![Uploading Screenshot 2021-03-30 at 3.32.00 PM.png…]()

**Comment by sharjeelahmed** [comment]
also scroll to item of collectionView is not working .

**Comment by amirdew** [comment]
Do you have this code in your view controller?
```swift
   override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        DispatchQueue.main.async { [weak self] in
            self?.collectionView?.performBatchUpdates({ [weak self] in
                self?.collectionView?.collectionViewLayout.invalidateLayout()
            })
        }
    }
```

**Comment by sharjeelahmed** [comment]
@amirdew yes

**Comment by amirdew** [comment]
Hmm, weird, could you reproduce the issue and share the code?

Try this too:
```swift
    var observation: NSKeyValueObservation?
    var lastBounds: CGRect?

    override func viewDidLoad() {
        super.viewDidLoad()

        observation = collectionView.observe(\.bounds) { [weak self] collectionView, _ in
            guard collectionView.bounds.size != self?.lastBounds?.size else { return }
            self?.lastBounds = collectionView.bounds
            DispatchQueue.main.async {
                collectionView.performBatchUpdates({
                    collectionView.collectionViewLayout.invalidateLayout()
                })
            }
        }
    }
```

**Comment by sharjeelahmed** [comment]
`class CategoryWithProductsViewController: BaseViewController {
	
	class func instantiateFromStoryboard() -> CategoryWithProductsViewController {
		return AppStoryboard.Campaign.viewController(viewControllerClass: CategoryWithProductsViewController.self)
	}
		
	@IBOutlet weak var collectionView: UICollectionView!
	var observation: NSKeyValueObservation?
	var lastBounds: CGRect?
	
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
		self.registerCollectionViewCells()
		self.configureCollectionView()
		
		observation = collectionView.observe(\.bounds) { [weak self] collectionView, _ in
					guard collectionView.bounds.size != self?.lastBounds?.size else { return }
					self?.lastBounds = collectionView.bounds
					DispatchQueue.main.async {
						collectionView.performBatchUpdates({
							collectionView.collectionViewLayout.invalidateLayout()
						})
					}
				}
    }
	
	private func configureCollectionView() {
		collectionView.isPagingEnabled = false
		collectionView.dataSource = self
		let layout = CollectionViewPagingLayout()
		layout.numberOfVisibleItems = 3
		collectionView.collectionViewLayout = layout
		collectionView.showsHorizontalScrollIndicator = false
		collectionView.clipsToBounds = false
		collectionView.backgroundColor = .clear
	}
	
	override func viewDidLayoutSubviews() {
			super.viewDidLayoutSubviews()
			DispatchQueue.main.async { [weak self] in
				self?.collectionView?.performBatchUpdates({ [weak self] in
					self?.collectionView?.collectionViewLayout.invalidateLayout()
				})
			}
		}
	
	func moveCollectionViewToIndex(index:Int){
		if self.array.indices.contains(index){
			DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
				self.collectionView.scrollToItem(at: IndexPath.init(row: index, section: 0), at: .right, animated: true)
			}
		}
	}
}

extension CategoryWithProductsViewController:UICollectionViewDataSource,UICollectionViewDelegate,UICollectionViewDelegateFlowLayout{
	
	func numberOfSections(in collectionView: UICollectionView) -> Int {
		return 1
	}
	
	func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
		return self.array.count
	}
	
	func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
		let cell = collectionView.dequeueReusableCell(withReuseIdentifier: String(describing: CategorySliderDealCollectionViewCell.self), for: indexPath) as!  CategorySliderDealCollectionViewCell		
		return cell
	}
	
}
`

`class CategorySliderDealCollectionViewCell: BaseCollectionViewCell,ScaleTransformView {
	var scaleOptions = ScaleTransformViewOptions(
		minScale: 0.60,
		   maxScale: 1.00,
		   scaleRatio: 0.40,
		   translationRatio: .init(x: 0.66, y: 0.20),
		   minTranslationRatio: .init(x: -5.00, y: -5.00),
		   maxTranslationRatio: .init(x: 2.00, y: 0.00),
		   keepVerticalSpacingEqual: true,
		   keepHorizontalSpacingEqual: true,
		   scaleCurve: .linear,
		   translationCurve: .linear,
		   shadowEnabled: false,
		   shadowColor: .clear,
		   shadowOpacity: 0,
		   shadowRadiusMin: 0,
		   shadowRadiusMax: 0,
		   shadowOffsetMin: .init(width: 0.00, height: 0),
		   shadowOffsetMax: .init(width: 0.00, height: 0),
		   shadowOpacityMin: 0,
		   shadowOpacityMax: 0,
		   blurEffectEnabled: false,
		   blurEffectRadiusRatio: 0.40,
		   blurEffectStyle: .light,
		   rotation3d: nil,
		   translation3d: nil
	   )

	@IBOutlet weak var imageViewCategory:UIImageView!
	override func awakeFromNib() {
		super.awakeFromNib()
		// Initialization code
		self.imageViewCategory.cornerRadius = 12
	}
	override func prepareForReuse() {
		super.prepareForReuse()
	}
}
extension CategorySliderDealCollectionViewCell{
	//implemented the delegate method of protocol ScaleTransformView
	
	func transform(progress: CGFloat) {
		self.applyScaleTransform(progress: progress)
		if progress == 0 {
			self.imageViewCategory.borderWidth = 2
			self.imageViewCategory.borderColor = UIColor.hexStringToUIColor(hex: "#BF9E4B")
		}else{
			self.imageViewCategory.borderWidth = 0
			self.imageViewCategory.borderColor = UIColor.clear
		}
	}
}
	
`

**Comment by sharjeelahmed** [comment]
` class CategoryWithProductsViewController: BaseViewController {
	class func instantiateFromStoryboard() -> CategoryWithProductsViewController {
		return AppStoryboard.Campaign.viewController(viewControllerClass: CategoryWithProductsViewController.self)
	}
		
	@IBOutlet weak var collectionView: UICollectionView!
	var observation: NSKeyValueObservation?
	var lastBounds: CGRect?
	
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
		self.registerCollectionViewCells()
		self.configureCollectionView()
		
		observation = collectionView.observe(\.bounds) { [weak self] collectionView, _ in
					guard collectionView.bounds.size != self?.lastBounds?.size else { return }
					self?.lastBounds = collectionView.bounds
					DispatchQueue.main.async {
						collectionView.performBatchUpdates({
							collectionView.collectionViewLayout.invalidateLayout()
						})
					}
				}
    }
	
	private func configureCollectionView() {
		collectionView.isPagingEnabled = false
		collectionView.dataSource = self
		let layout = CollectionViewPagingLayout()
		layout.numberOfVisibleItems = 3
		collectionView.collectionViewLayout = layout
		collectionView.showsHorizontalScrollIndicator = false
		collectionView.clipsToBounds = false
		collectionView.backgroundColor = .clear
	}
	
	override func viewDidLayoutSubviews() {
			super.viewDidLayoutSubviews()
			DispatchQueue.main.async { [weak self] in
				self?.collectionView?.performBatchUpdates({ [weak self] in
					self?.collectionView?.collectionViewLayout.invalidateLayout()
				})
			}
		}
	
	func moveCollectionViewToIndex(index:Int){
		if self.array.indices.contains(index){
			DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
				self.collectionView.scrollToItem(at: IndexPath.init(row: index, section: 0), at: .right, animated: true)
			}
		}
	}
}

extension CategoryWithProductsViewController:UICollectionViewDataSource,UICollectionViewDelegate,UICollectionViewDelegateFlowLayout{
	
	func numberOfSections(in collectionView: UICollectionView) -> Int {
		return 1
	}
	
	func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
		return self.array.count
	}
	
	func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
		let cell = collectionView.dequeueReusableCell(withReuseIdentifier: String(describing: CategorySliderDealCollectionViewCell.self), for: indexPath) as!  CategorySliderDealCollectionViewCell		
		return cell
	}
	
} `

` class CategorySliderDealCollectionViewCell: BaseCollectionViewCell,ScaleTransformView {
	var scaleOptions = ScaleTransformViewOptions(
		minScale: 0.60,
		   maxScale: 1.00,
		   scaleRatio: 0.40,
		   translationRatio: .init(x: 0.66, y: 0.20),
		   minTranslationRatio: .init(x: -5.00, y: -5.00),
		   maxTranslationRatio: .init(x: 2.00, y: 0.00),
		   keepVerticalSpacingEqual: true,
		   keepHorizontalSpacingEqual: true,
		   scaleCurve: .linear,
		   translationCurve: .linear,
		   shadowEnabled: false,
		   shadowColor: .clear,
		   shadowOpacity: 0,
		   shadowRadiusMin: 0,
		   shadowRadiusMax: 0,
		   shadowOffsetMin: .init(width: 0.00, height: 0),
		   shadowOffsetMax: .init(width: 0.00, height: 0),
		   shadowOpacityMin: 0,
		   shadowOpacityMax: 0,
		   blurEffectEnabled: false,
		   blurEffectRadiusRatio: 0.40,
		   blurEffectStyle: .light,
		   rotation3d: nil,
		   translation3d: nil
	   )

	@IBOutlet weak var imageViewCategory:UIImageView!
	override func awakeFromNib() {
		super.awakeFromNib()
		// Initialization code
		self.imageViewCategory.cornerRadius = 12
	}
	override func prepareForReuse() {
		super.prepareForReuse()
	}
}
extension CategorySliderDealCollectionViewCell{
	//implemented the delegate method of protocol ScaleTransformView
	
	func transform(progress: CGFloat) {
		self.applyScaleTransform(progress: progress)
		if progress == 0 {
			self.imageViewCategory.borderWidth = 2
			self.imageViewCategory.borderColor = UIColor.hexStringToUIColor(hex: "#BF9E4B")
		}else{
			self.imageViewCategory.borderWidth = 0
			self.imageViewCategory.borderColor = UIColor.clear
		}
	}
}
`

**Comment by sharjeelahmed** [comment]
```

 class CategoryWithProductsViewController: BaseViewController {
	class func instantiateFromStoryboard() -> CategoryWithProductsViewController {
		return AppStoryboard.Campaign.viewController(viewControllerClass: CategoryWithProductsViewController.self)
	}
		
	@IBOutlet weak var collectionView: UICollectionView!
	var observation: NSKeyValueObservation?
	var lastBounds: CGRect?
	
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
		self.registerCollectionViewCells()
		self.configureCollectionView()
		
		observation = collectionView.observe(\.bounds) { [weak self] collectionView, _ in
					guard collectionView.bounds.size != self?.lastBounds?.size else { return }
					self?.lastBounds = collectionView.bounds
					DispatchQueue.main.async {
						collectionView.performBatchUpdates({
							collectionView.collectionViewLayout.invalidateLayout()
						})
					}
				}
    }
	
	private func configureCollectionView() {
		collectionView.isPagingEnabled = false
		collectionView.dataSource = self
		let layout = CollectionViewPagingLayout()
		layout.numberOfVisibleItems = 3
		collectionView.collectionViewLayout = layout
		collectionView.showsHorizontalScrollIndicator = false
		collectionView.clipsToBounds = false
		collectionView.backgroundColor = .clear
	}
	
	override func viewDidLayoutSubviews() {
			super.viewDidLayoutSubviews()
			DispatchQueue.main.async { [weak self] in
				self?.collectionView?.performBatchUpdates({ [weak self] in
					self?.collectionView?.collectionViewLayout.invalidateLayout()
				})
			}
		}
	
	func moveCollectionViewToIndex(index:Int){
		if self.array.indices.contains(index){
			DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
				self.collectionView.scrollToItem(at: IndexPath.init(row: index, section: 0), at: .right, animated: true)
			}
		}
	}
}

extension CategoryWithProductsViewController:UICollectionViewDataSource,UICollectionViewDelegate,UICollectionViewDelegateFlowLayout{
	
	func numberOfSections(in collectionView: UICollectionView) -> Int {
		return 1
	}
	
	func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
		return self.array.count
	}
	
	func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
		let cell = collectionView.dequeueReusableCell(withReuseIdentifier: String(describing: CategorySliderDealCollectionViewCell.self), for: indexPath) as!  CategorySliderDealCollectionViewCell		
		return cell
	}
	
} `

` class CategorySliderDealCollectionViewCell: BaseCollectionViewCell,ScaleTransformView {
	var scaleOptions = ScaleTransformViewOptions(
		minScale: 0.60,
		   maxScale: 1.00,
		   scaleRatio: 0.40,
		   translationRatio: .init(x: 0.66, y: 0.20),
		   minTranslationRatio: .init(x: -5.00, y: -5.00),
		   maxTranslationRatio: .init(x: 2.00, y: 0.00),
		   keepVerticalSpacingEqual: true,
		   keepHorizontalSpacingEqual: true,
		   scaleCurve: .linear,
		   translationCurve: .linear,
		   shadowEnabled: false,
		   shadowColor: .clear,
		   shadowOpacity: 0,
		   shadowRadiusMin: 0,
		   shadowRadiusMax: 0,
		   shadowOffsetMin: .init(width: 0.00, height: 0),
		   shadowOffsetMax: .init(width: 0.00, height: 0),
		   shadowOpacityMin: 0,
		   shadowOpacityMax: 0,
		   blurEffectEnabled: false,
		   blurEffectRadiusRatio: 0.40,
		   blurEffectStyle: .light,
		   rotation3d: nil,
		   translation3d: nil
	   )

	@IBOutlet weak var imageViewCategory:UIImageView!
	override func awakeFromNib() {
		super.awakeFromNib()
		// Initialization code
		self.imageViewCategory.cornerRadius = 12
	}
	override func prepareForReuse() {
		super.prepareForReuse()
	}
}
extension CategorySliderDealCollectionViewCell{
	//implemented the delegate method of protocol ScaleTransformView
	
	func transform(progress: CGFloat) {
		self.applyScaleTransform(progress: progress)
		if progress == 0 {
			self.imageViewCategory.borderWidth = 2
			self.imageViewCategory.borderColor = UIColor.hexStringToUIColor(hex: "#BF9E4B")
		}else{
			self.imageViewCategory.borderWidth = 0
			self.imageViewCategory.borderColor = UIColor.clear
		}
	}
}

```

**Comment by amirdew** [comment]
Sorry I meant a stand-alone project or viewcontroller that I can simply run and see the issue.


I don't see anything wrong with this code so the problem might be somewhere else.

**Comment by amirdew** [comment]
I couldn't replicate the issue at the end, I just release a new version `1.0.0`.    
That might fix the problem.     
Check that and feel free to open a new ticket if needed.
