### ISSUE TITLE
How to get top most card's index

### ISSUE THREAD

**Issue by Happily-Hemu** [amirdew/CollectionViewPagingLayout#41]
I want to get the topmost card's index which is being displayed. Pl guide me on how I can get it with your library. Thanks.

**Comment by amirdew** [comment]
Hi,
on UIKit you can use `currentPage` on `CollectionViewPagingLayout`:
```swift
(collectionView.collectionViewLayout as? CollectionViewPagingLayout)?.currentPage
```
on SwiftUI you can use `selection`:

```swift
    @State private var currentPage: Page.ID?

    var body: some View {
        SnapshotPageView(pages, selection: $currentPage) { page in
                // page view
            }
     }
```

**Comment by Happily-Hemu** [comment]
I actually want to perform some sort of action on the card swipe with the visible card's data (i,e an API call). Is there any delegate method I can use which will notify me of the card swipe event along with your suggested code. So that I can get the index of the visible page and get details from my array that holds that data.

**Comment by amirdew** [comment]
Yes the delegate method mentioned 
at the end of this section

https://github.com/amirdew/CollectionViewPagingLayout/blob/master/HOW_TO_USE_UIKIT.md#control-current-page

**Comment by amirdew** [comment]
you can use UIScrollView delegate too
