### ISSUE TITLE
How to change aligment from center to left?

### ISSUE THREAD

**Issue by Nahatakyan** [amirdew/CollectionViewPagingLayout#42]
In all examples, paging is centered. Is there a way to change paging alignment to left and bottom? Like in the image.

<img width="843" alt="Screen Shot 2021-04-29 at 01 24 09" src="https://user-images.githubusercontent.com/35862561/116474473-9c3a8980-a889-11eb-9eb2-cc528ae74e16.png">

**Comment by amirdew** [comment]
Yes you can achieve this in few ways, the simplest one is just adjusting padding around your target view in the cell content view.
something like this:
```swift
func setup() {
        // You can use Autolayout too
        let cardFrame = CGRect(x: 0, y: 300, width: 100, height: 160)
        card = UIView(frame: cardFrame)
        card.backgroundColor = .gray
        contentView.addSubview(card)
    }
```
You also need to touch `anchorPoint` since you want to keep items on the same base line so
```swift
class MyCell: UICollectionViewCell, ScaleTransformView {

    var scaleOptions: ScaleTransformViewOptions {
        .init(
            minScale: 0.6,
            scaleRatio: 0.4,
            translationRatio: CGPoint(x: 0.66, y: 0)
        )
    }

    func transform(progress: CGFloat) {
        card.layer.anchorPoint = .init(x: 0.5, y: 1.5)
        applyScaleTransform(progress: progress)
    }
}
```

result:
![Simulator Screen Shot - iPod touch (7th generation) - 2021-04-29 at 12 47 18](https://user-images.githubusercontent.com/1938899/116539440-177f5800-a8e9-11eb-8fc3-5f7b406d0cb7.png)

**Comment by Nahatakyan** [comment]
Thank you!

**Comment by Nahatakyan** [comment]
Finnaly I get what I need with this:


    extension Cell: ScaleTransformView {
        var scaleOptions: ScaleTransformViewOptions {
            let minHeight: CGFloat = 220
            let minScale = minHeight / Self.cardSize.height
            let spacing: CGFloat = 16
            let translationRatioXDelta = spacing / cardView.frame.width
            return ScaleTransformViewOptions(
                minScale: minScale,
                scaleRatio: 1 - minScale,
                translationRatio: CGPoint(x: minScale + translationRatioXDelta, y: 0)
            )
        }

        func transform(progress: CGFloat) {
            let leftInset: CGFloat = 20
            let x = 0.5 - (leftInset / cardView.frame.width)
            let height = Self.cardSize.height - cardView.frame.height
            let y = 0.5 - (height / cardView.frame.height)
            cardView.layer.anchorPoint = CGPoint(x: x, y: y)
            applyScaleTransform(progress: progress)
        }
    }
