### ISSUE TITLE
perspective with stackPosition: .init(x: -1.00, y: 0.00)

### ISSUE THREAD

**Issue by fattalgazi** [amirdew/CollectionViewPagingLayout#45]
Hello again, 
I'm using .perspective stack transform with stackPosition: .init(x: -1.00, y: 0.00)
So instead of right listing of back cells, I put them on the left side.
However now, mouse gestures is not working as expected,
Please see attachment video:

https://user-images.githubusercontent.com/3602109/119030431-8c0e5980-b9b2-11eb-9551-dfd2aebe53fd.mov

I want to pop the top cell by swiping right, not swiping left. How to do that?

My whole configuration:

```
var stackOptions = StackTransformViewOptions(
    scaleFactor: 0.10,
    minScale: 0.20,
    maxScale: 1.00,
    maxStackSize: 6,
    spacingFactor: 0.08,
    maxSpacing: nil,
    alphaFactor: 0.15,
    bottomStackAlphaSpeedFactor: 0.90,
    topStackAlphaSpeedFactor: 0.30,
    perspectiveRatio: 0.30,
    shadowEnabled: true,
    shadowColor: .black,
    shadowOpacity: 0.10,
    shadowOffset: .zero,
    shadowRadius: 5.00,
    stackRotateAngel: 0.00,
    popAngle: 0.31,
    popOffsetRatio: .init(width: 2.00, height: 0.30),
    stackPosition: .init(x: -1.00, y: 0.00),
    reverse: false,
    blurEffectEnabled: false,
    maxBlurEffectRadius: 0.00,
    blurEffectStyle: .light
)
```
Thank you.

**Comment by amirdew** [comment]
hay you tried setting `reverse` to `true`? you might need to scroll to the end of scrollview though at the beginning

**Comment by fattalgazi** [comment]
Yes, it worked, first, I have reversed the collection view's data array, and then jumped to last cell with `setCurrentPage animated:false`, thank you!

**Comment by leynercastillo** [comment]
> Yes, it worked, first, I have reversed the collection view's data array, and then jumped to last cell with `setCurrentPage animated:false`, thank you!

Can you share how did you fix it? I'm trying to do the same, but with scroll vertical and swiping bottom.
