### ISSUE TITLE
Issue in reloading CollectionViewCell

### ISSUE THREAD

**Issue by Vignesh-Spark** [amirdew/CollectionViewPagingLayout#46]
when we reload  collection view using "collectionView.reloadData()", the cells disappears. After moving in the blank space the cell appears back

**Comment by amirdew** [comment]
if you can share a piece of code that reproduces the issue I can help better.        
Try this after reloadData, 
```swift
(self.collectionView.collectionViewLayout as? CollectionViewPagingLayout)?.invalidateLayoutInBatchUpdate()
```

**Comment by Vignesh-Spark** [comment]
> if you can share a piece of code that reproduces the issue I can help better.
> Try this after reloadData,
> 
> ```swift
> (self.collectionView.collectionViewLayout as? CollectionViewPagingLayout)?.invalidateLayoutInBatchUpdate()
> ```

Thank you so much for the fast replay "collectionView.reloadData()" worked now. There was one more issue that I faced. When we reload a single cell of the collection view using "collectionView.reloadItems(at: [IndexPath])" the cell reloads but after reloading user click/tap is not affected on the cell, After we move to other cell and come back the cell comes back to normal and responds to the click / tap

**Comment by amirdew** [comment]
Probably the same trick (`invalidateLayoutInBatchUpdate`) should work for that too, if it doesn't I'd need a sample code to investigate more

**Comment by Vignesh-Spark** [comment]
Just want to let every one know. when I disappearing cell after reload (self.collectionView.collectionViewLayout as? CollectionViewPagingLayout)?.invalidateLayoutInBatchUpdate() did the trick for me, but their was still some glitchy cell movement. Changed the above code to  collectionView?.performBatchUpdates({ [weak self] in
            self?.collectionView?.collectionViewLayout.invalidateLayout()
        }) , and then all the reload issues were long gone.
