### ISSUE TITLE
Vertical ScrollView with a horizontal CollectionViewPagingLayout

### ISSUE THREAD

**Issue by Zagho** [amirdew/CollectionViewPagingLayout#47]
The collectionView is working fine with your pod, but I am not able to scroll vertically in the storyboard when trying to scroll with my finger over the UICollectionView, I need to put my finger on other items and then scroll to let it work.
Any solution?

**Comment by amirdew** [comment]
I'm not sure if I understood the issue correctly, do you have a gesture/button in your cell?
could you make a simple project and share it here so I can investigate more.
