### ISSUE TITLE
How to create delays when user is paging?

### ISSUE THREAD

**Issue by bluepixeltech** [amirdew/CollectionViewPagingLayout#48]
Hi,

When the user is swiping pages, is there a way to create a delay before next page is displayed? Should I use the transform func for that?

**Comment by amirdew** [comment]
I'm not sure exactly what you want to achieve.
But I think you can achieve that using [UIViewPropertyAnimator](https://developer.apple.com/documentation/uikit/uiviewpropertyanimator)

You need to interrupt the animation when the user changes the direction or moves the finger faster.
in the transform function, you need to start the animation or adjust it if it's started already.

Not something straightforward but I think it's achievable!
Have fun! and share the result if you don't mind.
