### ISSUE TITLE
sizeForItemAt indexPath: IndexPath never called

### ISSUE THREAD

**Issue by id-main** [amirdew/CollectionViewPagingLayout#49]
NewWD.dataSource = self //coforms with UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout
        NewWD.delegate = self
        let layout = CollectionViewPagingLayout()
        layout.delegate = self // conforms with CollectionViewPagingLayoutDelegate
        layout.numberOfVisibleItems = 3 // default=nil means it's equal to number of items in CollectionView
        NewWD.collectionViewLayout = layout
        NewWD.isPagingEnabled = true 
//this function is never called
func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout:    UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let needH = self.NewWD.frame.height - 20
        let needW = needH * 0.56
        return CGSize(width: needW, height: needH)
    }

**Comment by amirdew** [comment]
The method you are referring to is defined in `UICollectionViewDelegateFlowLayout`.
This library is a different layout and has a different delegate: `CollectionViewPagingLayoutDelegate`. 
That method has nothing to do with this layout so it doesn't get called.

If you are looking for adjusting cell size, you should do that inside your cell. The cell size is always equal to the collection view size, you can consider the first subview of your cell as content view and use auto-layout to adjust the size.

See this issues https://github.com/amirdew/CollectionViewPagingLayout/issues/39 https://github.com/amirdew/CollectionViewPagingLayout/issues/42
