### ISSUE TITLE
Crash on iPhone 6s, ios 12.4

### ISSUE THREAD

**Issue by dvt282** [amirdew/CollectionViewPagingLayout#5]
I run example on iPhone 6s, ios 12.4 and choose option Fruits, It cash with reason:
UICollectionView received layout attributes for a cell with an index path that does not exist: <NSIndexPath: 0x2826b1220> {length = 2, path = 0 - 5}

**Comment by amirdew** [comment]
Hi, thanks for reporting the issue, we have an open pull request for this. [https://github.com/amirdew/CollectionViewPagingLayout/pull/3](url)
I'm going to close that and fix the issue in another pull request since I didn't receive  any update
