### ISSUE TITLE
How to change height of last visible cell

### ISSUE THREAD

**Issue by 3rnestocs** [amirdew/CollectionViewPagingLayout#50]
I have an `UICollectionView` with 4 visible items stacked with the `StackTransformView` conformance. I configured the stack appearance with this code 

```
StackTransformViewOptions(scaleFactor: 0.3, minScale: 0.2,
                                         spacingFactor: 0.07,
                                         popOffsetRatio: .init(width: 0, height: 3), reverse: true) 
```

The problem is that the last visible cell has an undesired spacingFactor. I want to change the spacing factor for only that last visible cell, is it possible?

**Comment by amirdew** [comment]
It is possible, but you should apply it manually

in the cell class: 
```swift
func transform(progress: CGFloat) {
        applyStackTransform(progress: progress) 
        // here check if it's the last cell, modify it
}
```
