### ISSUE TITLE
Build failed in Xcode 13 / iOS 15 Beta

### ISSUE THREAD

**Issue by skegget** [amirdew/CollectionViewPagingLayout#51]
I'm using Xcode 13 (Beta 5) and iOS 15 Beta and have just started using this package. However, as soon as I include the package in my project I'm getting "Build Failed" and a couple of warnings.

In total I get 10 swift compiler errors related to CollectionViewPagingLayout and two warnings, see attached print screen.

Any ideas? 

Thanks!

<img width="597" alt="Build Error" src="https://user-images.githubusercontent.com/31093687/131339683-14460443-b5a8-400b-8040-546bc383b4bc.png">

**Comment by amirdew** [comment]
I just tried it with Xcode Version 13.0 beta 5 (13A5212g)
Works fine! I tried it with SPM
[SampleProject.zip](https://github.com/amirdew/CollectionViewPagingLayout/files/7111421/SampleProject.zip)

**Comment by CristianMoisei** [comment]
This used to work in the betas but it doesn't work with the RC or the version from the App Store. I'm getting the same errors. One important thing to clarify is that this happens when **archiving**, but not when building.

![Screenshot 2021-09-23 at 10 21 11](https://user-images.githubusercontent.com/7927870/134475595-77dd1eba-bcd5-404c-a8ab-5576d90b8fbc.jpg)

**Comment by Sookie7** [comment]
> This used to work in the betas but it doesn't work with the RC or the version from the App Store. I'm getting the same errors. One important thing to clarify is that this happens when **archiving**, but not when building.
> 
> I have another project that is using v0.4.1 and that one archives fine. The one that is giving the errors is using v1.0.2
> I haven't tested to check what the latest working version is but this could be an interim solution for anyone who needs it.
> 
> ![Screenshot 2021-09-23 at 10 21 11](https://user-images.githubusercontent.com/7927870/134475595-77dd1eba-bcd5-404c-a8ab-5576d90b8fbc.jpg)

same issue, but I can't install v0.4.1

**Comment by CristianMoisei** [comment]
@Sookie7 have you tried setting it to exact version 0.4.1? Then you can File > Packages > Resolve Package Versions

![Screenshot 2021-09-23 at 23 52 19](https://user-images.githubusercontent.com/7927870/134589089-eca06613-116a-4c03-91a6-9a50c179536f.jpg)

**Comment by LeeTwelve** [comment]
@CristianMoisei this is a true way but not for me. I use `invalidateLayoutInBatchUpdate()` and 0.4.1 doesn't have this method.

**Comment by amirdew** [comment]
Explained here https://github.com/amirdew/CollectionViewPagingLayout/issues/54
Use `xcode13-no-swiftui` branch as a workaround
