### ISSUE TITLE
Next cell is not tappable. 

### ISSUE THREAD

**Issue by xLuciferSx** [amirdew/CollectionViewPagingLayout#52]
I've build an app which will allow user to like and share quotes by using your library but the problem is that after a swipe next cell action buttons are not capable. We've tried to fix this issue by using your delegate method but it is not working. 

Video attached - https://youtu.be/yVZlXM_TXbE

**Comment by amirdew** [comment]
Hey
In the video I see a red background
But you're saying the buttons aren't functional 

Anyway, the only thing you need to do is making sure zPosition is provided correctly for each cell

See https://github.com/amirdew/CollectionViewPagingLayout/blob/master/Lib/TransformableView.swift

func zPosition(progress: CGFloat) -> Int


I can help better if you share a simple version of your code
Or use one of the examples to replicate the issue

**Comment by xLuciferSx** [comment]
I'm using StackTransform and I have a red background to see if actual cell is moving but cell is not moving

**Comment by amirdew** [comment]
The cell doesn't move, the transform only applies to the 'cardView',
'cardView' is the first subview of the cel's 'contentView' by default, you can change it though,
See https://github.com/amirdew/CollectionViewPagingLayout/blob/master/Lib/Stack/StackTransformView.swift

But you don't need that you can just move all of the views to a subview

**Comment by xLuciferSx** [comment]
Here is my code which I am currently building. 
[CollectionViewPagingLayoutTest.zip](https://github.com/amirdew/CollectionViewPagingLayout/files/7160517/CollectionViewPagingLayoutTest.zip)

**Comment by xLuciferSx** [comment]
> Hey
> In the video I see a red background
> But you're saying the buttons aren't functional
> 
> Anyway, the only thing you need to do is making sure zPosition is provided correctly for each cell
> 
> See https://github.com/amirdew/CollectionViewPagingLayout/blob/master/Lib/TransformableView.swift
> 
> func zPosition(progress: CGFloat) -> Int
> 
> I can help better if you share a simple version of your code
> Or use one of the examples to replicate the issue

Thanks for your comment. I've played with Z position but it didn't help. Still buttons are not clickable after swipe.

**Comment by amirdew** [comment]
I just checked your code, I noticed you copied the code to your project so it was outdated or modified version.
I changed it to Swift package manager and everything works now.
Sorry for delay, I had a busy week

[CollectionViewPagingLayoutTest.zip](https://github.com/amirdew/CollectionViewPagingLayout/files/7186834/CollectionViewPagingLayoutTest.zip)

**Comment by xLuciferSx** [comment]
> I just checked your code, I noticed you copied the code to your project so it was outdated or modified version.
> I changed it to Swift package manager and everything works now.
> Sorry for delay, I had a busy week
> 
> [CollectionViewPagingLayoutTest.zip](https://github.com/amirdew/CollectionViewPagingLayout/files/7186834/CollectionViewPagingLayoutTest.zip)

Hi. Thank you very much! Now everything is working. I've got only few layout issues but i will try to fix them :) Thank you again!
