### ISSUE TITLE
XCode 13 Archiving Failed

### ISSUE THREAD

**Issue by jerrylin1002** [amirdew/CollectionViewPagingLayout#54]
We can build and run on development; but always failed when archiving on production. 
![圖片](https://user-images.githubusercontent.com/5171308/134682625-91812fa8-91db-470f-85a4-25d9464aba3c.png)
![圖片](https://user-images.githubusercontent.com/5171308/134682669-75ad0f06-6a96-481f-8b7a-b3b025c27edc.png)
![圖片](https://user-images.githubusercontent.com/5171308/134682737-46563ed8-f111-48c0-b22c-96c250e4ca5f.png)
![圖片](https://user-images.githubusercontent.com/5171308/134682818-b382490c-11f5-4099-a1a2-f9c5c8d0d07b.png)
![圖片](https://user-images.githubusercontent.com/5171308/134682851-d28dca65-9e72-4cb8-839a-789a78e5de88.png)

**Comment by amirdew** [comment]
Unfortunately, this is an Xcode 13 issue, from release note: 
```
Known Issues
Swift libraries may fail to build for iOS targets that use armv7. (74120874)
Workaround: Increase the platform dependency of the package to v12 or later.

Swift libraries depending on Combine may fail to build for targets including armv7 and i386 architectures. (82183186, 82189214)
Workaround: Use an updated version of the library that isn’t impacted (if available) or remove armv7 and i386 support (for
example, increase the deployment target of the library to iOS 11 or higher).
```
The same thing is happening to other libraries https://github.com/onevcat/Kingfisher/issues/1802#issuecomment-919815919

What we can do is opening a branch and remove Combine and SwiftUI for supporting old iOS versions
I'll do that

**Comment by amirdew** [comment]
Use this [xcode13-no-swiftui](https://github.com/amirdew/CollectionViewPagingLayout/tree/xcode13-no-swiftui) branch

**Comment by skegget** [comment]
I'm far from an expert but I noticed this in the release notes of Xcode 13.2 Beta:
- "Fixed an issue that prevented Swift libraries depending on Combine from building for targets including armv7 and i386 architectures. (82183186, 82189214)"

Could that be a solution?

**Comment by dinhletrieuduong** [comment]
I can't find the [xcode13-no-swiftui](https://github.com/amirdew/CollectionViewPagingLayout/tree/xcode13-no-swiftui) branch. How can I fix it? (I support iOS 10 with Xcode 13)

**Comment by amirdew** [comment]
@dinhletrieuduong I restored the branch

**Comment by dinhletrieuduong** [comment]
Thanks, it's worked
