### ISSUE TITLE
Issue On Card Stack Jump On First Swipe Up

### ISSUE THREAD

**Issue by prashantgSpaceO** [amirdew/CollectionViewPagingLayout#62]
https://drive.google.com/drive/folders/1Bd1390w9pvN6dBGFl1qYxt8a7mXB23fX?usp=sharing

I have attached a video link of the issue on the card stack.
When we try to swipe up the card for the first time it bounds up the whole stack rather than just swiping up the only card we have selected.

**Comment by amirdew** [comment]
Thanks for reporting this issue

**Comment by prashantgSpaceO** [comment]
You are most welcome @amirdew 
one thing I want to mention is that I also fixed this issue by 
`//calling viewDidLayoutSubviews() on the last line of the configureCollectionView()`
