### ISSUE TITLE
Xcode 13 Archive failed for target iOS 14 in SwiftUI project

### ISSUE THREAD

**Issue by alschmut** [amirdew/CollectionViewPagingLayout#63]
# Bug report

I am using CollectionViewPagingLayout for a SwiftUI project with deployment target iOS 14.0, but when archiving the project using version 1.0.3 via SPM, I am getting around 20 errors about not finding SwiftUI. As of what I understood, the [xcode13-no-swiftui](https://github.com/amirdew/CollectionViewPagingLayout/tree/xcode13-no-swiftui) branch is meant for projects that support older iOS versions and don't need SwiftUI or Combine, but I do need SwiftUI and Combine compatibility.

Is there a workaround to fix this?

<img width="300" src="https://user-images.githubusercontent.com/23529226/141946095-b32673b1-2759-4918-ad71-6bcfc7ffe911.jpeg">

**Comment by amirdew** [comment]
Super annoying bug in Xcode 13!
I create a new branch and set the target to iOS 13
branch name: `target-ios-13`

I hope they fix this issue in the next Xcode version
