### ISSUE TITLE
Invalid numberOfVisibleItems

### ISSUE THREAD

**Issue by LinXunFeng** [amirdew/CollectionViewPagingLayout#65]
Hey
As follows, I set `numberOfVisibleItems` to `3`, but it not work

Any ideas?
Thanks!

```swift
let layout = CollectionViewPagingLayout()
layout.numberOfVisibleItems = 3
layoutTypeCollectionView.collectionViewLayout = layout
```

![image](https://user-images.githubusercontent.com/19367531/148370540-30367e83-991b-43b1-9c30-f223d47f81ce.png)

**Comment by amirdew** [comment]
Seems to work fine.
Note that there are two collection views on this page, if you want to change the one for cards change this one: https://github.com/amirdew/CollectionViewPagingLayout/blob/03ada0527826710ab67e48626d7fea57032c2d33/Samples/PagingLayoutSamples/Modules/UIKit/Shapes/ShapesViewController.swift#L115

<img src="https://user-images.githubusercontent.com/1938899/150672560-1d0e415e-c8c5-4590-abc9-a597d9951986.png" width=300>
