### ISSUE TITLE
How can we scroll the cards in StackPageView vertically instead of scrolling in horizontal direction?

### ISSUE THREAD

**Issue by Kripali-Agrawal** [amirdew/CollectionViewPagingLayout#66]

**Comment by amirdew** [comment]
by setting scroll direction to vertical like this: https://github.com/amirdew/CollectionViewPagingLayout/blob/03ada0527826710ab67e48626d7fea57032c2d33/Samples/PagingLayoutSamples/Modules/UIKit/Cards/CardsViewController.swift#L85

**Comment by sahibhussain** [comment]
this just change the scroll behaviour not the layout. My use case is i want the layout to be vertical.
