### ISSUE TITLE
Vertical orientation of items

### ISSUE THREAD

**Issue by agattringer** [amirdew/CollectionViewPagingLayout#72]
Is it possible to arrange the UICollectionViewCells in a vertical orientation?
Changing the `scrollDirection` only changes how I interact with the UICollectionView itself.
The items keep being shown from left to right.

**Comment by amirdew** [comment]
Yes it's possible, for instance, the [cards example](https://github.com/amirdew/CollectionViewPagingLayout/blob/master/Samples/PagingLayoutSamples/Modules/UIKit/Cards/Cell/CardCollectionViewCell.swift)
You would need to touch the transform code
