### ISSUE TITLE
RTL support for layout

### ISSUE THREAD

**Issue by iZeDeveloper** [amirdew/CollectionViewPagingLayout#74]
if i set collectionflowlayout to this library, my collectionview ignores the semantics set by me. e.g i wanted RTL but when i set it let it again go the semantic property and always shows Left to right.
Any idea how to fix it ?

**Comment by AndrewKaz98** [comment]
Any luck on solving this issue ?!

**Comment by amirdew** [comment]
Unfortunately, that's not supported by this library. 
Mentioned in the [limitations](https://github.com/amirdew/CollectionViewPagingLayout#limitations) section
