### ISSUE TITLE
Strange SwiftUI navigation behavior when using CollectionViewPagingLayout

### ISSUE THREAD

**Issue by stephensilber** [amirdew/CollectionViewPagingLayout#77]
I'm attaching a barebones project that can reproduce the bug I'm referring to below.

When I use this package, my app can no longer present views without a weird side effect (using `.sheet` or a custom UIKit `.bottomSheet` modifier). The flow goes like this:

[ContentView]
     [CollectionViewPagingLayout] → [NavigationLink] _(user tap)_ → [DetailView] _(user tap)_ → [PresentedSheetView]

This all works as expected. When the user dismisses `PresentedSheetView`, it also pops `DetailView` off of the `NavigationView` stack and brings the user back to `ContentView`. I have isolated this to be 100% related to this package in the project below.

This package is leaps and bounds better than any other horizontal paging package I've seen (likely because it is backed by a collection view instead of buggy SwiftUI gesture handlers). Any guidance on how we can work around or fix this would be greatly appreciated.

_Note: This screen cap includes the entire project source code if you don't feel like downloading the project_
[CollectionPageReproduceBug.zip](https://github.com/amirdew/CollectionViewPagingLayout/files/9426923/CollectionPageReproduceBug.zip)

https://user-images.githubusercontent.com/845497/186728975-21eb69a9-0e9d-40b3-a684-65b63067384a.mp4

**Comment by amirdew** [comment]
Thanks for submitting the video and the project, and sorry for the late response.
The reason is that SwiftUI re-renders the views inside `ScalePageView` so `NavigationLink` loses its state!

If we move the `NavigationLink` out of `ScalePageView` it gets fixed:

```swift
struct ContentView: View {
    @State var currentPage: String? = nil
    @State var items: [Item] = [
        .random(),
        .random()
    ]
    @State var activeItem: Item.ID?

    var body: some View {
        VStack {
            Spacer()
            ForEach(items) { item in
                NavigationLink(destination: DetailView(), tag: item.id, selection: $activeItem) {}
            }
            ScalePageView(items, selection: $currentPage) { quest in
                Button {
                    activeItem = quest.id
                } label: {
                    Text("Click me to go to detail")
                        .font(.headline.bold())
                        .foregroundColor(.black)
                        .padding()
                        .background(.orange)
                        .cornerRadius(16)
                        .shadow(radius: 8)
                }
            }
            .options(TransformOptions.home)
            .pagePadding(
                vertical: .absolute(100),
                horizontal: .absolute(80)
            )
        }
        .padding()
    }
}
```
